version: 0.2

phases:
  pre_build:
    commands:
      - (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 021891603561.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t ecr1 .
      - docker tag ecr1:latest 021891603561.dkr.ecr.ap-south-1.amazonaws.com/ecr1:latest
  post_build:
    commands:
      - docker push 021891603561.dkr.ecr.ap-south-1.amazonaws.com/ecr1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
